FST: InvertedIndex Class Reference
InvertedIndex Class Reference
Inverted index class for managing a collection of documents and their word frequencies.
#include <inverted_index.h>
Public Member Functions
InvertedIndex ()=default
Default constructor for InvertedIndex.
void UpdateDocumentBase (DocId doc, std::map< std::string, size_t > words)
Updates the document base with a new set of documents.
std::vector< Entry > GetWordCount (const std::string &word) const
Get word count for a specific word in each document.
std::map< std::string, size_t > GetDocWords (DocId id) const
Get the frequency dictionary for a specific document.
Static Public Member Functions
static InvertedIndex FromFiles (const std::vector< std::string > &files)
Constructs an InvertedIndex from files.
Private Attributes
std::map< DocId, std::map< std::string, size_t > > _docs
std::map< std::string, std::vector< Entry > > _freq_dictionary
TEST_FRIENDS
Detailed Description
Inverted index class for managing a collection of documents and their word frequencies.
Definition at line 35 of file inverted_index.h.
Constructor & Destructor Documentation
InvertedIndex()
InvertedIndex::InvertedIndex () default
Default constructor for InvertedIndex.
Member Function Documentation
FromFiles()
InvertedIndex InvertedIndex::FromFiles (const std::vector< std::string > & files) static
Constructs an InvertedIndex from files.
Parameters
files A vector of file paths to read documents from.
Returns
An InvertedIndex object populated with documents from the specified files.
Definition at line 38 of file inverted_index.cpp.
{
     log_enter();
     BS::thread_pool pool;
     log_info("Using ", pool.get_thread_count(), " threads for processing files...");
     std::vector<std::future<std::map<std::string, size_t>>> futures;
     for (const auto& file : files) {
         futures.push_back(pool.submit_task([&] { return handle_file(file.c_str()); }));
     }
     InvertedIndex ii;
     for (size_t i = 0; i < futures.size(); ++i) {
         ii.UpdateDocumentBase(i, futures[i].get());
     }
     return ii;
 }
References log_enter, log_info, and UpdateDocumentBase().
Referenced by main().
GetDocWords()
std::map< std::string, size_t > InvertedIndex::GetDocWords (DocId id) const
Get the frequency dictionary for a specific document.
Parameters
id The document ID for which to retrieve the frequency dictionary.
Returns
A map where keys are words and values are their counts in the specified document. If the document ID does not exist, an empty map is returned.
Definition at line 80 of file inverted_index.cpp.
{
     auto it = _docs.find(id);
     if (it != _docs.end()) {
         return it->second;
     }
     return {};
 }
References _docs.
Referenced by SearchServer::SearchOne().
GetWordCount()
std::vector< Entry > InvertedIndex::GetWordCount (const std::string & word) const
Get word count for a specific word in each document.
Parameters
word The word to search for in the documents.
Returns
A vector of Entry objects containing the document ID and count of the word in each document.
Definition at line 72 of file inverted_index.cpp.
{
     auto it = _freq_dictionary.find(word);
     if (it != _freq_dictionary.end()) {
         return it->second;
     }
     return {};
 }
References _freq_dictionary.
Referenced by SearchServer::SearchOne().
UpdateDocumentBase()
void InvertedIndex::UpdateDocumentBase (DocId doc, std::map< std::string, size_t > words)
Updates the document base with a new set of documents.
Parameters
doc The document index to update.
words A map containing unique words and their counts in the documents.
Note
This method will replace the existing document at the specified index.
Definition at line 53 of file inverted_index.cpp.
{
     log_enter();
     log_debug("Update base for doc id: ", doc);
     for (auto& [word, count] : words) {
         auto& freqs = _freq_dictionary[word];
         auto entry = std::find_if(freqs.begin(), freqs.end(),
                                   [doc](const Entry& e) { return e.doc_id == doc; });
         log_debug("word: \"", word, "\", cnt: ", count);
         if (entry != freqs.end()) {
             entry->count = count;
         } else {
             freqs.emplace_back(doc, count);
         }
     }
     if (!_docs.insert_or_assign(doc, std::move(words)).second) {
         log_warn("Document '", doc, "' overriden!");
     };
 }
References _docs, _freq_dictionary, log_debug, log_enter, and log_warn.
Referenced by FromFiles().
Member Data Documentation
_docs
std::map<DocId, std::map<std::string, size_t> > InvertedIndex::_docs private
Definition at line 74 of file inverted_index.h.
Referenced by GetDocWords(), and UpdateDocumentBase().
_freq_dictionary
std::map<std::string, std::vector<Entry> > InvertedIndex::_freq_dictionary private
Definition at line 75 of file inverted_index.h.
Referenced by GetWordCount(), and UpdateDocumentBase().
TEST_FRIENDS
InvertedIndex::TEST_FRIENDS private
Definition at line 76 of file inverted_index.h.
The documentation for this class was generated from the following files:
include/inverted_index.h
src/inverted_index.cpp